name: Compiling Clang's executable, for i686 Ubuntu 18

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Downloading input objects
        run: wget https://github.com/advancedwebdeveloper/clang11rc1_cross_i686/releases/download/0.1/batch_clang.zip
      - name: Decompressing required object files
        run: unzip batch_clang.zip
      - name: List the files
        run: ls
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: upload-archive
          path: cc1_main.cpp.o
